version: '2'
services:
  web:
    build: .
    command: /go/src/github.com/pstuifzand/socket-io-chat/socket-io-chat
    ports:
     - "5000:5000"
    depends_on:
     - redis
  redis:
    image: redis
